# 1. Pytorch fundamentals

In [1]:
import torch
torch.__version__

'1.10.0+cu102'

## Scalers

In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

## Vectors

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

How many square brackets does vector have?

Another important concept for tensors is their shape attribute. The shape tells you how the elements inside them are arranged.

Let's check out the shape of vector.

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

## Matrix

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

## Tensor

In [16]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [20]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.9920, 0.0104, 0.7635, 0.8537],
         [0.8528, 0.4617, 0.1718, 0.3041],
         [0.7745, 0.8805, 0.4923, 0.4625]]),
 torch.float32)

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeroes and Ones

In [25]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like

In [27]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Operations

In [29]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
tensor * 10

tensor([10, 20, 30])

In [31]:
# Matrix
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [32]:
tensor.ndim

1

In [33]:
# element wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [34]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning (shape errors)

In [35]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [36]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [37]:
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## Reshaping, stacking, squeezing and unsqueezing

In [40]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [41]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [42]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [43]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

How about removing all single dimensions from a tensor?

To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).

In [44]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [47]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [60]:
# Create tensor with specific shape
x_original = torch.rand(size=(1, 2, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([1, 2, 3])
New shape: torch.Size([3, 1, 2])


In [61]:
x_permuted

tensor([[[0.8474, 0.4563]],

        [[0.8988, 0.9719]],

        [[0.1105, 0.3968]]])

In [62]:
x_original

tensor([[[0.8474, 0.8988, 0.1105],
         [0.4563, 0.9719, 0.3968]]])

## Indexing

In [69]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [64]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [72]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [73]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

## Reproducibility

In [76]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors on GPU

In [77]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [78]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [79]:
# Count number of devices
torch.cuda.device_count()


1

In [80]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to CPU

In [81]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [82]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [83]:
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

## Exercise

In [89]:
rnd1 = torch.rand(size=(7,7))
rnd2 = torch.rand(size=(1,7))

In [90]:
rnd1

tensor([[0.1568, 0.2083, 0.3289, 0.1054, 0.9192, 0.4008, 0.9302],
        [0.6558, 0.0766, 0.8460, 0.3624, 0.3083, 0.0850, 0.0029],
        [0.6431, 0.3908, 0.6947, 0.0897, 0.8712, 0.1330, 0.4137],
        [0.6044, 0.7581, 0.9037, 0.9555, 0.1035, 0.6258, 0.2849],
        [0.4452, 0.1258, 0.9554, 0.1330, 0.7672, 0.6757, 0.6625],
        [0.2297, 0.9545, 0.6099, 0.5643, 0.0594, 0.7099, 0.4250],
        [0.2709, 0.9295, 0.6115, 0.2234, 0.2469, 0.4761, 0.7792]])

In [91]:
rnd2

tensor([[0.3722, 0.2147, 0.3288, 0.1265, 0.6783, 0.8870, 0.0293]])

In [93]:
torch.matmul(rnd1, rnd2.T)

tensor([[1.2308],
        [0.8691],
        [1.2840],
        [1.4394],
        [1.6629],
        [1.2447],
        [1.1423]])

In [97]:
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 

rnd1 = torch.rand(size=(7,7))
rnd2 = torch.rand(size=(1,7))
torch.matmul(rnd1, rnd2.T)

tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])

In [98]:
torch.manual_seed(1234)

rnd1 = torch.rand(size=(2,3))
rnd2 = torch.rand(size=(2,3))

rnd1_gpu = rnd1.to(device)
rnd2_gpu = rnd2.to(device)

rnd1_gpu

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [99]:
rnd2_gpu

tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')

In [102]:
result = torch.matmul(rnd1, rnd2.T)
result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

In [103]:
result.max()

tensor(0.5617)

In [104]:
result.min()

tensor(0.3647)

In [105]:
result.argmax()

tensor(3)

In [106]:
result.argmin()

tensor(0)

In [118]:
torch.manual_seed(7)

rnd = torch.rand(size=(1, 1, 1, 10))
rnd.shape

torch.Size([1, 1, 1, 10])

In [119]:
rnd = rnd.squeeze(dim=0).squeeze(dim=0).squeeze(dim=0)
rnd.shape

torch.Size([10])